goodreads/api/urls.py
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet


app_name = 'api'

router = DefaultRouter()
router.register('reviews', BookReviewsViewSet, basename='review')
urlpatterns = router.urls

goodreads/goodreads/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings
from .views import landing_page, home_page

urlpatterns = [
    path("", landing_page, name='landing_page'),
    path('home/', home_page, name='home_page'),
    path("user/", include("user.urls")),
    path('books/', include("books.urls")),
    path("api/", include("api.urls")),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goodreads/user/urls.py
from django.urls import path
from user.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = 'user'
urlpatterns = [
    path("register/", RegisterView.as_view(), name='register'),
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile_edit")
]

goodreads/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="default_profile_pic.jpg")

goodreads/user/forms.py
from django import forms
from user.models import CustomUser


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()

        return user


# important for runserver
class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=128)


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_picture')

goodreads/user/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View

from user.forms import UserCreateForm, UserUpdateForm


class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            "form": create_form
        }
        return render(request, "user/register.html", context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
            create_form.save()
            return redirect('user:login')
        else:
            create_form = UserCreateForm()
            context = {
                "form": create_form
            }
            return render(request, "user/register.html", context)


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()
        return render(request, "user/login.html", {"login_form": login_form})

    def post(self, request):
        print(request.POST['username'], request.POST['password'])
        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)

            messages.success(request, "You have successfully loggen in")

            return redirect("books:list")
        else:
            return render(request, "user/login.html", {"login_form": login_form})


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "user/profile.html", {"user": request.user})


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, "You have successfully logged out.")
        return redirect("landing_page")


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)
        return render(request, "user/profile_edit.html", {"form": user_update_form})

    def post(self, request):
        user_update_form = UserUpdateForm(
            instance=request.user,
            data=request.POST,
            files=request.FILES
        )

        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request, 'You have successfully updated your profile.')
            return  redirect("user:profile")

        return render(request, "user/profile_edit.html", {"form": user_update_form})

goodreads/user/templates/user/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login Page{% endblock %}

{% block content %}
    <h3>Login </h3>

    <div class="row">
        <div class="col-4">
            <form method="post">
             {% csrf_token %}
            {{ login_form | crispy}}
            <button class="btn btn-primary">Log in</button> <span class="ms-3">No account? Please, <a href="{% url 'user:register' %}">get registered</a></span>
            </form>
        </div>
    </div>
{% endblock %}

goodreads/user/templates/user/profile.html
{% extends "base.html"%}
{% block title %}Profile Page{% endblock%}

{% block content%}

        <div class="image d-flex flex-column justify-content-center align-items-center">
            <button class="btn btn-secondary">
                <img class="profile-pic" alt="Profile picture" src="{{ user.profile_picture.url }}">
            </button>
            <span class="name mt-3">{{ user.first_name}} {{ user.last_name}}</span>
            <span class="idd">{{ user.username }}</span>
             <span class="idd">{{ user.email }}</span>
            <div class="d-flex mt-2">  <a href="{% url 'user:profile_edit'%}">edit profile</a></div>
            <div class="px-2 rounded mt-4 date"><span class="join">{{ user.date_joined | date:"M d ,Y"}}</span></div>
        </div>

{% endblock %}

goodreads/user/templates/user/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

  <h2> Edit Profile  </h2>

  <div class="row">
    <div class="col-4">
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}

{{ form | crispy }}
  <button class="btn btn-primary">Save changes</button>
</form>
    </div>
  </div>
{% endblock %}

goodreads/user/templates/user/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Register page{% endblock %}

{% block content %}
<h2>
  Register
</h2>
<div class="row">
        <div class="col-4">
<form method="post" action="{% url 'user:register' %}">
        {% csrf_token %}
    {{ form | crispy }}

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
        </div>
</div>
{% endblock %}