goodreads/api/urls.py
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet


app_name = 'api'

router = DefaultRouter()
router.register('reviews', BookReviewsViewSet, basename='review')
urlpatterns = router.urls

goodreads/books/urls.py
from django.urls import path
from books.views import BooksView, BookDetailView, AddReviewView, EditReviewView, ConfirmDeleteReviewView, \
    DeleteReviewView

app_name = "books"
urlpatterns = [
    path("", BooksView.as_view(), name="list"),
    path("<int:id>/", BookDetailView.as_view(), name='detail'),
    path("<int:id>/reviews/", AddReviewView.as_view(), name="reviews"),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name="edit-review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/confirm/",
         ConfirmDeleteReviewView.as_view(),
         name="confirm-delete-review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/",
         DeleteReviewView.as_view(),
         name="delete-review")
]

goodreads/goodreads/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings
from .views import landing_page, home_page

urlpatterns = [
    path("", landing_page, name='landing_page'),
    path('home/', home_page, name='home_page'),
    path("user/", include("user.urls")),
    path('books/', include("books.urls")),
    path("api/", include("api.urls")),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goodreads/user/urls.py
from django.urls import path
from user.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = 'user'
urlpatterns = [
    path("register/", RegisterView.as_view(), name='register'),
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile_edit")
]

goodreads/templates/base.html
{% load static %}
{% url 'home_page' as home_page_url %}
{% url 'books:list' as books_page_url %}
{% url 'user:profile' as profile_page_url %}
{% url 'user:profile-edit' as profile_edit_page_url %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Goodreads Clone{% endblock %}</title>
        <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link href="{% static 'css/main.css'%}" rel="stylesheet" type="text/css">

</head>
<body class="mx-5">


<nav class="navbar navbar-expand-lg navbar-dark big-primary mb-2" style="background-color: pink;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'landing_page'%}">Goodreads Clone</a>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link  {% if request.path == home_page_url %} active {% endif %}"  aria-current="page" href="{{home_page_url }}">Home</a>
            </li>
          <li class="nav-item">
              <a class="nav-link {% if request.path == books_page_url %} active {% endif %}" aria-current="page" href="{{ books_page_url }}">Books</a>
            </li>
      </ul>


        <div class="me-5">
            {% if request.user.is_authenticated %}
            <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle {% if request.path == profile_page_url or request.path == profile_edit_page_url %} active {% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      {{ request.user.username }}
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{{ profile_page_url }}">Profile</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'user:logout'%}">Log out</a></li>
                  </ul>
                </li>
            </ul>

                {% else %}
             <a class="btn btn-outline-info" href="{% url 'user:login' %}">Login</a>
            {% endif %}
        </div>

    </div>
  </div>
</nav>



<div class="container">
{% if messages %}
    <div class="mt-4">
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    </div>


    {% endif %}

{% block content %}{% endblock %}
</div>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

goodreads/templates/home.html
    {% extends 'base.html'%}

  {% block title %} Home page {% endblock %}

 {% block content %}
    <h2>All Reviews</h2>

    {% for review in page_obj %}
   <div class="container posts-content">
    <div class="row">
        <div class="col-lg-6">
            <div class="card mb-4">
              <div class="card-body">
                <div class="media mb-3">
                    <img src="{{ review.user.profile_picture.url }}"
                         class="d-block ui-w-40 rounded-circle" >
                  <div class="media-body ml-3">
                   {{ review.user.username }}
                    <div class="text-muted small">{{review.created_at | date:"M d ,Y"}}</div>
                  </div>
                </div>
                <p>
                  {{ review.comment | truncatechars:300}}
                </p>
                  <img class="cover-pic " src="{{ review.book.cover_picture.url }}">
              </div>

            </div>
        </div>

    </div>
</div>
    {% endfor %}

        <nav>
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number}}">Previous
            </a></li>
            {% endif %}

            <li class="page-item active">
                <a href="#" class="page-link">{{ page_obj.number }}</a>
            </li>

            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number}}">Next</a></li>
            <li class="page-item"><a class="page-link" href="?page{{ page_obj.paginator.num_pages}}">Last&raquo;</a></li>
            {% endif %}
        </ul>
    </nav>

 {% endblock %}

goodreads/templates/landing.html
{% extends "base.html" %}

{% block content %}
            <h1>Landing pages</h1>

<p>
    Goodreads is the world’s largest site for readers and book recommendations. Our mission is to help people find and share books they love. Goodreads launched in January 2007.
    See what books your friends are reading.
Track the books you're reading, have read, and want to read.
Check out your personalized book recommendations. Our recommendation engine analyzes 20 billion data points to give suggestions tailored to your literary tastes.
Find out if a book is a good fit for you from our community’s reviews.When I was in second grade, I discovered the Hardy Boys series. Ever since, I've loved to read — both for fun and to improve my mind. And I'm always looking for the next great book.
One afternoon while I was scanning a friend's bookshelf for ideas, it struck me: when I want to know what books to read, I'd rather turn to a friend than any random person or bestseller list.
So I decided to build a website – a place where I could see my friends' bookshelves and learn about what they thought of all their books. Elizabeth, my co-founder (and now my wife) wrote the site copy and I wrote the code. We started in my living room, motivated by the belief that there was a better way to discover and discuss good books, and that we could build it.
Goodreads is that site. It is a place where you can see what your friends are reading and vice versa. You can create "bookshelves" to organize what you've read (or want to read). You can comment on each other's reviews. You can find your next favorite book. And on this journey with your friends you can explore new territory, gather information, and expand your mind.
Knowledge is power, and power is best shared among readers.
</p>
{% endblock %}